### ISSUE TITLE
Possible collaborator

### ISSUE THREAD

**Issue by Lyla-Fischer** [ahopkins/pydiggy#2]
I'm still exploring the library and seeing what it's currently capable of, but if you have things for me to work on sooner rather than later, I'd be happy to pick them up. Looking forward to the collaboration!

**Comment by Lyla-Fischer** [comment]
One thing that might drive adoption (and therefore more incidental contributions and community support) is supporting older versions of python. Being full-featured is probably more important, but I'm just thinking about my own assumption of python3.5, and the pain of updating python in larger projects. What do you think?

**Comment by ahopkins** [comment]
@Lyla-Fischer first of all.... welcome! I really appreciate the offer and willingness to join. I am using `dgraph` (and therefore `pydiggy`) on a side project. So, over the last month or two I have not been too involved with it. I am hopeful to get a nice push towards cleaning up the repo and stabilizing the API thru this Summer.

In regards to the failing tests, and the question of how to get started, I think first thing I know I want to do is clean up the repo some and add some more documentation and code comments. I will work on that some tonight.

--- 

I do understand your comment about supporting Python 3.5. And, perhaps you are right. Bu I think t it will take **A LOT** of work to do that. I specifically built the package to work with type annotations, and, at that using some features that are specifically available in Python 3.7. I suppose it would be possible to do, but some of the annotation support pre-3.7 isn't quite there. 

I think before we get to that, there's some code cleanup and refactoring that might be needed to make it an easier package to maintain. I sort of was more interested in getting it working, so the code complexity is a bit higher than I would like. Perhaps after looking thru the code you have some ideas on how to do it?

---

With that said, I am happy to have you help. Let me compose some of my thoughts on some of what is needed to get things going and I will be happy to hear your thoughts as well.

**Comment by Lyla-Fischer** [comment]
Thanks for the welcome! Ya, I've currently got a couple of things going on myself, but I was hoping to start using the code as it stands and maybe documenting my way through the usage? Having you do the first draft and my functioning as a proof-reader might make some sense for that. You both know how this stuff works, and you can comment on design philosophies that I might not pick up on from reading the code. It sounded like you've got most of the basic functionality down already, it's just not in the most maintainable state? If you can get the code to the point where I can start my own development cycle (that is, get it working again), then I might be able to help with some of the documentation and code-clean-up (wherever you feel comfortable). It would help get me on-boarded to the existing state of the codebase as I prepare to contribute in other ways as well.

**Comment by Lyla-Fischer** [comment]
Also, I appreciate how much work it can be to get your thoughts organized on what is needed, and I'm going to be depending on your leadership for that significantly. I do have an application in mind, but I'm new to graph databases, so I'm going to have a significant learning curve.

**Comment by ahopkins** [comment]
@Lyla-Fischer, I [pushed a commit ](https://github.com/ahopkins/pydiggy/commit/12c5468e119c007870a7b9308f3dea517b28060e) that cleaned up the tests so they are passing again, and also ran `black` and `isort` on the repo. 

I'll probably also add a `tox.ini` that is [similar to the one on `sanic`](https://github.com/huge-success/sanic/blob/master/tox.ini)

**Comment by ahopkins** [comment]
I have added some more comments on things that need to be addressed. In addition, I added [an example](https://github.com/ahopkins/pydiggy/blob/master/examples/subclass.py) that sort of shows how I am using `pydiggy` on a project. 

You [mentioned wanting a more ORM-like](https://github.com/dgraph-io/pydgraph/issues/68#event-2366160282) package to go along with Dgraph. This is sort of one way that it could be achieved. It still requires you to predefine queries (or at least parts of them), but it may be somewhat helpful as it is one step closer to be able to do something like:

```python
people = Person.filter(family=99)
```

I think that before `pydiggy` adopted anything like this, there is still some work to be done in terms of stabilizing the API, and making sure that there is a good correlation between all the data types and directives, and also filling out the test suite.

Maybe we also could work to make the `subclass` example more abstract so that those queries can be dynamic. I do feel, however, that in the end querying is not something that is strongly suited for Python. The general principle of `pydiggy` is that data is fetched from the DB and stored in memory objects to be acted upon.

In my example linked to above, this would likely fail:

```python
adam = Person()
print(adam.father)
```

That is until either: (1) a new object was created and linked to as my father, or (2) was queried from the DB.

```python
adam = Person()
adam.father = Person()

or

adam = Person.get(1)
# assuming there is a query like in the example that would go out and fetch parents
```

**Comment by ahopkins** [comment]
With that all said...

My suggestion to you @Lyla-Fischer, before messing around too deeply with the `subclass.py` example, play around with something more like [the `basic.py` example](https://github.com/ahopkins/pydiggy/blob/master/examples/basic.py). I think this will show you a little more how to create, manipulate, and persist objects.

**Comment by Lyla-Fischer** [comment]
I just made a pull request that addresses the sanitation issue, and opened a bunch of issues that I thought about while trying to understand the code well enough to DRY up the code in that pull request. 

In other news: Do you happen to have a chat handle on a service somewhere, so that I might be able to ask questions about the codebase if you happen to be available? I'm still a little bit confused about the NodeMeta class, but I feel silly opening an issue in order to ask about it.

**Comment by ahopkins** [comment]
Gitter? `@ahopkins`
